Repository AY2021S2-CS2113T-F08-2/tp, pull requests merged in 2021-04, with the labels that each got.

#188 Updated and standardised Nurse Schedule UG
  docs/UserGuide.md
  docs/images/NurseScheduleHelp.png
  docs/images/NurseScheduleReturn.png
Labels: type.Task

#194 V2.0 DoctorAppt Bug Fix 1/4/21
  src/main/java/seedu/logic/errorchecker/DoctorAppointmentChecker.java
  src/main/java/seedu/logic/instance/DoctorAppointmentInstance.java
  src/main/java/seedu/storage/DoctorAppointmentStorage.java
  src/main/java/seedu/ui/DoctorAppointmentUI.java
Labels: priority.Medium, severity.Low

#196 Nurse Schedule UG updates
  docs/UserGuide.md
Labels: priority.High

#207 added simple logging
  src/main/java/seedu/logic/instance/NurseScheduleInstance.java
  src/main/java/seedu/logic/parser/NurseSchedulesParser.java
  src/main/java/seedu/storage/NurseScheduleStorage.java
Labels: priority.High

#209 getting started with logging
  src/main/java/seedu/duke/Constants.java
  src/main/java/seedu/logic/parser/NurseSchedulesParser.java
  src/main/java/seedu/storage/NurseScheduleStorage.java
Labels: priority.High

#210 added more JUnit tests to Nurse Schedules
  src/main/java/seedu/logic/command/NurseScheduleActions.java
  src/main/java/seedu/logic/parser/NurseSchedulesParser.java
  src/test/java/seedu/nurseschedules/NurseScheduleActionsTest.java
  src/test/java/seedu/nurseschedules/NurseScheduleCheckerTest.java
  src/test/java/seedu/nurseschedules/NurseSchedulesParserTest.java
Labels: type.Task, type.enhacement

#212 added more in-depth logging
  src/main/java/seedu/logic/command/NurseScheduleActions.java
  src/main/java/seedu/logic/instance/NurseScheduleInstance.java
Labels: type.Task

#217 Post PED bug fixes
  docs/UserGuide.md
  src/main/java/seedu/logic/errorchecker/NurseScheduleChecker.java
  src/main/java/seedu/logic/instance/NurseScheduleInstance.java
  src/main/java/seedu/logic/parser/NurseSchedulesParser.java
  src/main/java/seedu/storage/NurseScheduleStorage.java
  src/test/java/seedu/nurseschedules/NurseScheduleCheckerTest.java
Labels: priority.High

#286 Post PED bug fixes/UG edits #2
  docs/UserGuide.md
  src/main/java/seedu/exceptions/nurseschedules/DuplicateScheduleException.java
  src/main/java/seedu/exceptions/nurseschedules/InvalidScheduleException.java
  src/main/java/seedu/logic/command/Command.java
  src/main/java/seedu/logic/command/NurseScheduleActions.java
  src/main/java/seedu/logic/command/nurseschedule/NurseScheduleAdd.java
  src/main/java/seedu/logic/command/nurseschedule/NurseScheduleDelete.java
  src/main/java/seedu/logic/errorchecker/NurseScheduleChecker.java
Labels: priority.High, severity.Low, type.Task

#288 Updated DG of NurseSchedules
  docs/DeveloperGuide.md
  docs/images/ArchitectureDiagram.png
  src/main/java/seedu/logic/command/NurseScheduleActions.java
Labels: priority.High

#290 Trim inputs, updated DG with indentation
  docs/DeveloperGuide.md
  src/main/java/seedu/logic/parser/NurseSchedulesParser.java
Labels: priority.High, severity.Medium

#293 Bugfix for whitespace
  src/main/java/seedu/exceptions/patient/InvalidPatientAgeException.java
  src/main/java/seedu/exceptions/staff/InvalidStaffAgeException.java
  src/main/java/seedu/logic/command/StaffAggregation.java
  src/main/java/seedu/logic/command/staff/StaffList.java
  src/main/java/seedu/logic/errorchecker/MainChecker.java
  src/main/java/seedu/logic/errorchecker/PatientChecker.java
  src/main/java/seedu/logic/errorchecker/StaffChecker.java
  src/main/java/seedu/logic/parser/StaffParser.java
  src/main/java/seedu/storage/StaffStorage.java
  src/test/java/seedu/staff/StaffParserTest.java
Labels: priority.Medium, severity.Low

#294 Bugfix inconsistent find error message with patient
  src/main/java/seedu/logic/command/StaffAggregation.java
  src/main/java/seedu/logic/command/staff/StaffFind.java
  src/main/java/seedu/logic/command/staff/StaffList.java
  src/main/java/seedu/ui/StaffUI.java
Labels: severity.Medium

#295 v2.1 Bugfix for Smart Command Function
  src/main/java/seedu/logic/parser/StartMenuParser.java
  src/main/java/seedu/ui/UI.java
Labels: priority.High, severity.High

#299 Bugfix
  src/main/java/seedu/logic/command/StaffAggregation.java
  src/main/java/seedu/logic/command/staff/StaffDelete.java
  src/main/java/seedu/logic/command/staff/StaffList.java
  src/main/java/seedu/logic/errorchecker/StaffChecker.java
  src/main/java/seedu/logic/parser/StaffParser.java
  src/main/java/seedu/ui/StaffUI.java
  src/main/java/seedu/ui/UI.java
Labels: priority.Medium

#302 Add HealthVault Logger and Bug Fixes
  .gitignore
  src/main/java/seedu/duke/Constants.java
  src/main/java/seedu/logger/HealthVaultLogger.java
  src/main/java/seedu/logic/errorchecker/PatientChecker.java
  src/main/java/seedu/logic/instance/PatientInstance.java
  src/main/java/seedu/logic/parser/PatientParser.java
  src/main/java/seedu/storage/PatientStorage.java
Labels: priority.High, severity.Medium, type.Bug, type.enhacement

#305 Nurse Schedule DG #1
  docs/DeveloperGuide.md
  src/main/java/seedu/logic/parser/NurseSchedulesParser.java
Labels: type.Task

#307 Standardised logging for nurse schedules
  data/logs/HealthVaultLogs.log.lck
  src/main/java/seedu/logic/instance/NurseScheduleInstance.java
  src/main/java/seedu/logic/parser/NurseSchedulesParser.java
  src/main/java/seedu/model/nurseschedule/NurseScheduleList.java
  src/main/java/seedu/storage/NurseScheduleStorage.java
Labels: priority.High

#309 V2.1 Doctor Appointment Logging + list/all function
  data/logs/HealthVaultLogs.log.1
  data/logs/HealthVaultLogs.log.1.lck
  data/logs/HealthVaultLogs.log.2
  src/main/java/seedu/exceptions/EmptyListException.java
  src/main/java/seedu/logic/errorchecker/DoctorAppointmentChecker.java
  src/main/java/seedu/logic/instance/DoctorAppointmentInstance.java
  src/main/java/seedu/logic/parser/DoctorAppointmentParser.java
  src/main/java/seedu/model/doctorappointment/AppointmentList.java
  src/main/java/seedu/model/doctorappointment/DoctorAppointment.java
  src/main/java/seedu/storage/DoctorAppointmentStorage.java
  src/main/java/seedu/ui/DoctorAppointmentUI.java
Labels: priority.Medium, severity.Medium

#311 Adding Staff Testing
  src/main/java/seedu/exceptions/staff/WrongStaffIDException.java
  src/main/java/seedu/logic/command/staff/StaffFind.java
  src/main/java/seedu/logic/errorchecker/StaffChecker.java
  src/main/java/seedu/storage/StaffStorage.java
  src/test/java/seedu/staff/StaffCheckerTest.java
  src/test/java/seedu/staff/StaffParserTest.java
Labels: priority.Medium

#315 Update Patient DG to fit the format
  docs/DeveloperGuide.md
Labels: priority.Medium

#317 update section 1.0 of DG
  docs/DeveloperGuide.md
Labels: priority.Medium

#318 Updated Staff JavaDoc Comments
  src/main/java/seedu/exceptions/CorruptedFileException.java
  src/main/java/seedu/exceptions/DuplicateIDException.java
  src/main/java/seedu/exceptions/EmptyListException.java
  src/main/java/seedu/exceptions/ExcessInputException.java
  src/main/java/seedu/exceptions/IDNotFoundException.java
  src/main/java/seedu/exceptions/IllegalCharacterException.java
  src/main/java/seedu/exceptions/InsufficientInputException.java
  src/main/java/seedu/exceptions/InvalidDateException.java
  src/main/java/seedu/exceptions/InvalidGenderException.java
  src/main/java/seedu/exceptions/InvalidIDException.java
  src/main/java/seedu/exceptions/InvalidIntegerException.java
  src/main/java/seedu/exceptions/NoInputException.java
  src/main/java/seedu/exceptions/UnrecognizedCommandException.java
  src/main/java/seedu/exceptions/staff/InvalidStaffAgeException.java
  src/main/java/seedu/exceptions/staff/WrongListInputException.java
  src/main/java/seedu/exceptions/staff/WrongStaffIDException.java
  src/main/java/seedu/logic/command/staff/StaffAdd.java
  src/main/java/seedu/logic/command/staff/StaffDelete.java
  src/main/java/seedu/logic/command/staff/StaffFind.java
  src/main/java/seedu/logic/command/staff/StaffHelp.java
  src/main/java/seedu/logic/command/staff/StaffList.java
  src/main/java/seedu/logic/command/staff/StaffReturn.java
  src/main/java/seedu/logic/errorchecker/StaffChecker.java
  src/main/java/seedu/logic/instance/StaffInstance.java
  src/main/java/seedu/logic/parser/StaffParser.java
  src/main/java/seedu/model/staff/Staff.java
  src/main/java/seedu/model/staff/StaffList.java
  src/main/java/seedu/storage/StaffStorage.java
  src/main/java/seedu/ui/StaffUI.java
Labels: priority.Medium

#324 DG edits, minor code edits
  docs/DeveloperGuide.md
  docs/diagrams/Model.drawio
  docs/images/Model.png
  src/main/java/seedu/logic/command/nurseschedule/NurseScheduleAddCommand.java
  src/main/java/seedu/logic/command/nurseschedule/NurseScheduleDeleteCommand.java
  src/main/java/seedu/logic/command/nurseschedule/NurseScheduleHelpCommand.java
  src/main/java/seedu/logic/command/nurseschedule/NurseScheduleListCommand.java
  src/main/java/seedu/logic/command/nurseschedule/NurseScheduleReturnCommand.java
  src/main/java/seedu/logic/errorchecker/NurseScheduleChecker.java
  src/main/java/seedu/logic/parser/NurseSchedulesParser.java
  src/main/java/seedu/model/nurseschedule/NurseSchedule.java
  src/main/java/seedu/model/nurseschedule/NurseScheduleList.java
  src/test/java/seedu/nurseschedules/NurseScheduleListCommandTest.java
Labels: type.Task

#326 V2.1 Java CI Bux fix
  data/DoctorAppointment.txt
  data/logs/HealthVaultLogs.log.lck
  src/main/java/seedu/exceptions/doctorappointment/AppointmentIDTakenException.java
  src/main/java/seedu/exceptions/doctorappointment/DocIDNotFoundException.java
  src/main/java/seedu/exceptions/doctorappointment/DocIdNotFoundException.java
  src/main/java/seedu/exceptions/doctorappointment/FileCreatingErrorException.java
  src/main/java/seedu/exceptions/doctorappointment/InvalidDocIDException.java
  src/main/java/seedu/exceptions/doctorappointment/InvalidGenderException.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentAddCommand.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentDeleteCommand.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentHelpCommand.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentListCommand.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentReturnCommand.java
  src/main/java/seedu/logic/errorchecker/DoctorAppointmentChecker.java
  src/main/java/seedu/logic/errorchecker/MainChecker.java
  src/main/java/seedu/logic/instance/DoctorAppointmentInstance.java
  src/main/java/seedu/logic/parser/DoctorAppointmentParser.java
  src/main/java/seedu/logic/parser/StartMenuParser.java
  src/main/java/seedu/model/doctorappointment/AppointmentList.java
  src/main/java/seedu/model/doctorappointment/DoctorAppointment.java
  src/main/java/seedu/storage/DoctorAppointmentStorage.java
  src/main/java/seedu/ui/DoctorAppointmentUI.java
Labels: priority.Low

#328 JAVACI for command/startmenu
  src/main/java/seedu/logic/command/startmenu/ToStaffInstance.java
  src/main/java/seedu/storage/NurseScheduleStorage.java
  src/main/java/seedu/ui/NurseScheduleUI.java
Labels: type.Task

#330 minor DG edits to NurseSchedules
  docs/DeveloperGuide.md
Labels: type.Task

#332 Fix patient checkstyle errors
  src/main/java/seedu/duke/Constants.java
  src/main/java/seedu/exceptions/patient/InvalidFieldsNumberException.java
  src/main/java/seedu/exceptions/patient/InvalidIDLengthException.java
  src/main/java/seedu/exceptions/patient/InvalidIDTypeException.java
  src/main/java/seedu/exceptions/patient/InvalidIDValueException.java
  src/main/java/seedu/exceptions/patient/InvalidIdLengthException.java
  src/main/java/seedu/exceptions/patient/InvalidIdTypeException.java
  src/main/java/seedu/exceptions/patient/InvalidIdValueException.java
  src/main/java/seedu/exceptions/patient/InvalidPatientAgeException.java
  src/main/java/seedu/logic/command/Command.java
  src/main/java/seedu/logic/command/patient/PatientAddCommand.java
  src/main/java/seedu/logic/command/patient/PatientDeleteCommand.java
  src/main/java/seedu/logic/command/patient/PatientFindCommand.java
  src/main/java/seedu/logic/command/patient/PatientHelpCommand.java
  src/main/java/seedu/logic/command/patient/PatientListCommand.java
  src/main/java/seedu/logic/command/patient/PatientReturnCommand.java
  src/main/java/seedu/logic/errorchecker/PatientChecker.java
  src/main/java/seedu/logic/parser/PatientParser.java
  src/main/java/seedu/model/patient/Patient.java
  src/main/java/seedu/model/patient/PatientList.java
  src/main/java/seedu/storage/PatientStorage.java
  src/main/java/seedu/ui/PatientUI.java
Labels: priority.Medium, severity.Medium

#333 add more checkstyle error fixes
  src/main/java/seedu/logic/command/patient/PatientAddCommand.java
  src/main/java/seedu/logic/errorchecker/PatientChecker.java
  src/main/java/seedu/logic/parser/PatientParser.java
  src/main/java/seedu/model/patient/Patient.java
  src/main/java/seedu/ui/PatientUI.java
Labels: priority.Medium, severity.Medium

#334 V2.1 Added JavaDoc to Doctor Appointment
  src/main/java/seedu/exceptions/doctorappointment/DocIdNotFoundException.java
  src/main/java/seedu/exceptions/doctorappointment/InvalidGenderException.java
  src/main/java/seedu/exceptions/doctorappointment/WrongAptIDFormatException.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentAddCommand.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentDeleteCommand.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentHelpCommand.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentListCommand.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentReturnCommand.java
  src/main/java/seedu/logic/errorchecker/DoctorAppointmentChecker.java
  src/main/java/seedu/logic/instance/DoctorAppointmentInstance.java
  src/main/java/seedu/logic/parser/DoctorAppointmentParser.java
  src/main/java/seedu/model/doctorappointment/AppointmentList.java
  src/main/java/seedu/model/doctorappointment/DoctorAppointment.java
  src/main/java/seedu/storage/DoctorAppointmentStorage.java
Labels: priority.Medium

#341 V2.1 Doctor Appointment Junit Test updated
  src/main/java/seedu/logic/instance/DoctorAppointmentInstance.java
  src/test/java/seedu/doctorappointments/DoctorAppointmentCheckerParserTest.java
  src/test/java/seedu/doctorappointments/DoctorAppointmentCheckerTest.java
Labels: priority.Medium

#343 V2.1 Doctor Appointment Junit Test update after revert issue
  src/main/java/seedu/logic/instance/DoctorAppointmentInstance.java
  src/test/java/seedu/doctorappointments/DoctorAppointmentCheckerParserTest.java
  src/test/java/seedu/doctorappointments/DoctorAppointmentCheckerTest.java
Labels: priority.High

#344 no message
  src/test/java/seedu/nurseschedules/NurseSchedulesParserTest.java
Labels: type.Task

#345 V2.1 Updated JavaCI for Doctor Appointment
  src/main/java/seedu/exceptions/doctorappointment/DocIdNotFoundException.java
  src/main/java/seedu/exceptions/doctorappointment/WrongAptIdFormatException.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentDeleteCommand.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentListCommand.java
  src/main/java/seedu/logic/errorchecker/DoctorAppointmentChecker.java
  src/main/java/seedu/model/doctorappointment/AppointmentList.java
  src/main/java/seedu/storage/DoctorAppointmentStorage.java
  src/main/java/seedu/ui/DoctorAppointmentUI.java
Labels: priority.Medium

#347 update javadoc
  .gitignore
  src/main/java/seedu/duke/HealthVault.java
  src/main/java/seedu/logger/HealthVaultLogger.java
  src/main/java/seedu/logic/command/Command.java
  src/main/java/seedu/logic/command/patient/PatientAddCommand.java
  src/main/java/seedu/logic/command/patient/PatientDeleteCommand.java
  src/main/java/seedu/logic/command/patient/PatientFindCommand.java
  src/main/java/seedu/logic/command/patient/PatientHelpCommand.java
  src/main/java/seedu/logic/command/patient/PatientListCommand.java
  src/main/java/seedu/logic/command/patient/PatientReturnCommand.java
  src/main/java/seedu/logic/errorchecker/PatientChecker.java
  src/main/java/seedu/logic/instance/PatientInstance.java
  src/main/java/seedu/logic/parser/PatientParser.java
  src/main/java/seedu/logic/parser/StartMenuParser.java
  src/main/java/seedu/model/patient/Patient.java
  src/main/java/seedu/model/patient/PatientList.java
  src/main/java/seedu/storage/PatientStorage.java
  src/main/java/seedu/ui/PatientUI.java
  src/main/java/seedu/ui/UI.java
Labels: priority.Medium, severity.Low, type.Bug

#349 add more logging
  src/main/java/seedu/logic/errorchecker/PatientChecker.java
  src/main/java/seedu/logic/instance/PatientInstance.java
  src/main/java/seedu/logic/parser/PatientParser.java
  src/main/java/seedu/storage/PatientStorage.java
Labels: priority.Medium, type.enhacement

#352 Added NurseScheduleListSD to DG
  docs/DeveloperGuide.md
  docs/diagrams/NurseScheduleListSD.png
  docs/diagrams/NurseScheduleListSD.puml
  docs/team/alexandertan.md
Labels: priority.High

#355 Updated Product website and About Us page
  docs/AboutUs.md
  docs/README.md
  docs/team/alexandertanjunan.md
Labels: priority.High

#357 Update Logic Component
  docs/DeveloperGuide.md
  docs/diagrams/LogicComponent.png
  docs/diagrams/LogicComponent.puml
Labels: priority.Medium, severity.Medium

#358 Update Errors in DG
  docs/DeveloperGuide.md
  docs/diagrams/ExampleCommandPackage.png
  docs/diagrams/ExampleCommandPackage.puml
  docs/diagrams/LogicComponent.png
  docs/diagrams/LogicComponent.puml
Labels: priority.High, severity.High, type.Bug

#359 Small updates to PPP
  docs/team/alexandertanjunan.md
Labels: priority.High

#360 V2.1 updated DA Java CI
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentAddCommand.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentDeleteCommand.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentListCommand.java
  src/main/java/seedu/logic/errorchecker/DoctorAppointmentChecker.java
  src/main/java/seedu/model/doctorappointment/AppointmentList.java
  src/main/java/seedu/ui/DoctorAppointmentUI.java
Labels: priority.Low

#361 V2.1 updated DA Java CI
  src/main/java/seedu/ui/DoctorAppointmentUI.java
Labels: priority.Low

#362 V2.1 updated DA Java CI
  src/main/java/seedu/ui/DoctorAppointmentUI.java
Labels: priority.Low

#364 Added proposed features section
  docs/DeveloperGuide.md
Labels: type.Task

#365 Update alexandertanjunan.md
  docs/team/alexandertanjunan.md
Labels: type.Task

#367 Add design considerations to DG
  docs/DeveloperGuide.md
Labels: priority.Medium, severity.Medium, type.enhacement

#371 Edited all checkstyle for exceptions and Staff
  src/main/java/seedu/exceptions/DuplicateIdException.java
  src/main/java/seedu/exceptions/ExcessInputException.java
  src/main/java/seedu/exceptions/HealthVaultException.java
  src/main/java/seedu/exceptions/IDNotFoundException.java
  src/main/java/seedu/exceptions/IdNotFoundException.java
  src/main/java/seedu/exceptions/InsufficientInputException.java
  src/main/java/seedu/exceptions/InvalidDateException.java
  src/main/java/seedu/exceptions/InvalidGenderException.java
  src/main/java/seedu/exceptions/InvalidIdException.java
  src/main/java/seedu/exceptions/InvalidIntegerException.java
  src/main/java/seedu/exceptions/UnrecognizedCommandException.java
  src/main/java/seedu/exceptions/staff/InvalidStaffAgeException.java
  src/main/java/seedu/exceptions/staff/WrongListInputException.java
  src/main/java/seedu/exceptions/staff/WrongStaffIdException.java
  src/main/java/seedu/logic/command/Command.java
  src/main/java/seedu/logic/command/nurseschedule/NurseScheduleAddCommand.java
  src/main/java/seedu/logic/command/staff/StaffListCommand.java
  src/main/java/seedu/logic/command/staff/StaffReturnCommand.java
  src/main/java/seedu/logic/errorchecker/DoctorAppointmentChecker.java
  src/main/java/seedu/logic/errorchecker/PatientChecker.java
  src/main/java/seedu/logic/errorchecker/StaffChecker.java
  src/main/java/seedu/logic/instance/StaffInstance.java
  src/main/java/seedu/logic/parser/StaffParser.java
  src/main/java/seedu/model/staff/Staff.java
  src/main/java/seedu/model/staff/StaffList.java
  src/main/java/seedu/storage/StaffStorage.java
  src/test/java/seedu/staff/StaffCheckerTest.java
Labels: priority.High

#373 Update PPP and fixed bugs in DG
  docs/DeveloperGuide.md
  docs/diagrams/LogicComponent.png
  docs/diagrams/LogicComponent.puml
  docs/team/chiamjiaen.md
Labels: priority.Medium, severity.Medium, type.enhacement

#382 Fix exception inconsistencies
  .gitignore
  src/main/java/seedu/duke/Constants.java
  src/main/java/seedu/exceptions/InsufficientInputException.java
  src/main/java/seedu/exceptions/patient/InvalidFieldsNumberException.java
  src/main/java/seedu/exceptions/patient/InvalidIdLengthException.java
  src/main/java/seedu/exceptions/patient/InvalidIdTypeException.java
  src/main/java/seedu/exceptions/patient/InvalidIdValueException.java
  src/main/java/seedu/exceptions/patient/InvalidPatientAgeException.java
  src/main/java/seedu/exceptions/patient/InvalidPatientIdException.java
  src/main/java/seedu/logic/errorchecker/PatientChecker.java
  src/main/java/seedu/logic/instance/PatientInstance.java
  src/main/java/seedu/storage/PatientStorage.java
  src/main/java/seedu/ui/UI.java
Labels: priority.Medium, severity.Medium, type.Bug

#386 Java CI checkstyletest fix
  src/test/java/seedu/nurseschedules/NurseScheduleCheckerTest.java
  src/test/java/seedu/nurseschedules/NurseScheduleListCommandTest.java
  src/test/java/seedu/nurseschedules/NurseSchedulesParserTest.java
Labels: priority.High

#387 Updated Checkstyle for Staff Test
  src/test/java/seedu/doctorappointments/DoctorAppointmentCheckerTest.java
  src/test/java/seedu/patient/PatientParserTest.java
  src/test/java/seedu/staff/StaffCheckerTest.java
  src/test/java/seedu/staff/StaffParserTest.java
Labels: priority.Medium

#388 update to swtich statements
  docs/diagrams/LogicComponent.puml
  src/main/java/seedu/logic/errorchecker/DoctorAppointmentChecker.java
  src/main/java/seedu/logic/errorchecker/patientchecker/PatientChecker.java
  src/main/java/seedu/logic/errorchecker/patientchecker/utils/CommandInputTypeLength.java
  src/main/java/seedu/logic/parser/PatientParser.java
  src/main/java/seedu/storage/PatientStorage.java
  src/main/java/seedu/ui/InventoryUI.java
  src/main/java/seedu/ui/UI.java
Labels: priority.Medium, severity.Low

#394 add optimal healthvault viewing dimensions to UG
  .gitignore
  docs/UserGuide.md
Labels: priority.Medium, type.Bug

#395 fix minor UG bugs
  docs/UserGuide.md
Labels: priority.Medium, severity.Medium, type.Bug

#400 DA bug fixes
  data/DoctorAppointment.txt
  src/main/java/seedu/exceptions/doctorappointment/DoctorIdDoesNotExistException.java
  src/main/java/seedu/exceptions/doctorappointment/WrongIdFormatException.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentDeleteCommand.java
  src/main/java/seedu/logic/errorchecker/DoctorAppointmentChecker.java
  src/main/java/seedu/logic/instance/DoctorAppointmentInstance.java
  src/main/java/seedu/model/doctorappointment/AppointmentList.java
Labels: priority.Low

#402 Fixed corrupted staff file
  src/main/java/seedu/logic/errorchecker/DoctorAppointmentChecker.java
  src/main/java/seedu/logic/errorchecker/NurseScheduleChecker.java
  src/main/java/seedu/logic/instance/NurseScheduleInstance.java
  src/main/java/seedu/storage/DoctorAppointmentStorage.java
  text-ui-test/EXPECTED.TXT
Labels: severity.High

#404 Bugfix
  data/DoctorAppointment.txt
  src/main/java/seedu/logic/instance/StaffInstance.java
Labels: severity.High

#408 Minor edits to NurseScheduleStorage
  src/main/java/seedu/model/nurseschedule/NurseScheduleList.java
  src/main/java/seedu/storage/NurseScheduleStorage.java
Labels: priority.High

#409 Add positive/negative test cases to NS DG
  docs/DeveloperGuide.md
Labels: priority.High

#410 V2.1 update Doctor Appointment Exception for List/delete
  data/DoctorAppointment.txt
  src/main/java/seedu/duke/Constants.java
  src/main/java/seedu/exceptions/doctorappointment/WrongDocIdFormatException.java
  src/main/java/seedu/exceptions/doctorappointment/WrongIdFormatForDeleteException.java
  src/main/java/seedu/exceptions/doctorappointment/WrongIdFormatForListException.java
  src/main/java/seedu/logic/errorchecker/DoctorAppointmentChecker.java
  src/main/java/seedu/model/doctorappointment/AppointmentList.java
  src/test/java/seedu/doctorappointments/DoctorAppointmentCheckerTest.java
Labels: priority.Medium

#411 DG DA update
  docs/DeveloperGuide.md
  src/main/java/seedu/logic/errorchecker/DoctorAppointmentChecker.java
Labels: priority.Medium

#413 improved UG and fix typos in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/PatientAdd.jpg
  docs/images/PatientDelete.PNG
  docs/images/PatientFindID.jpg
  docs/images/PatientFindName.jpg
  docs/images/PatientHelp.jpg
  docs/images/PatientList.jpg
  docs/images/PatientReturn.PNG
  docs/images/PatientWelcome.PNG
  src/main/java/seedu/ui/PatientUI.java
Labels: priority.Medium, severity.Medium, type.Bug, type.enhacement

#414 Edited output and fixed find
  data/DoctorAppointment.txt
  src/main/java/seedu/logic/command/staff/StaffListCommand.java
  src/main/java/seedu/logic/command/staff/StaffReturnCommand.java
  src/main/java/seedu/logic/instance/StaffInstance.java
  src/main/java/seedu/model/staff/StaffList.java
  src/main/java/seedu/ui/StaffUI.java
Labels: priority.Medium

#417 Java CI GREEN TICK YAYYYYYY
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#420 PPP updates
  docs/team/alexandertanjunan.md
Labels: priority.High
