Repository AY2021S2-CS2113T-F08-2/tp, pull requests merged in 2021-03, with the labels that each got.

#21 Fixed Imports and added JUnit tests
  README.md
  src/main/java/seedu/nurseschedules/NurseSchedule.java
  src/main/java/seedu/nurseschedules/NurseScheduleActions.java
  src/main/java/seedu/nurseschedules/NurseScheduleInstance.java
  src/main/java/seedu/nurseschedules/NurseScheduleStorage.java
  src/main/java/seedu/nurseschedules/parser/Parser.java
  src/test/java/nurseschedules/parser/ParserTest.java
  src/test/java/seedu/duke/NurseScheduleInstanceTest.java
Labels: priority.High

#33 Slight UI changes and some error handling
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/nurseschedules/NurseScheduleActions.java
  src/main/java/seedu/nurseschedules/NurseScheduleInstance.java
  src/main/java/seedu/nurseschedules/parser/Parser.java
Labels: type.Task

#35 Doctor Appointment Storage functionality
  data/DoctorAppointmentList.txt
  src/main/java/seedu/doctorappointments/AppointmentActions.java
  src/main/java/seedu/doctorappointments/DoctorAppointment.java
  src/main/java/seedu/doctorappointments/DoctorAppointmentInstance.java
  src/main/java/seedu/doctorappointments/Parser.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/exceptions/EmptyListException.java
  src/main/java/seedu/duke/storage/DoctorAppointmentStorage.java
  src/main/java/seedu/duke/ui/UI.java
Labels: priority.High

#39 Chiam jia en exception handling1.0
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/exceptions/DukeException.java
  src/main/java/seedu/duke/exceptions/patient/duplicateIDException.java
  src/main/java/seedu/duke/exceptions/patient/invalidIDLengthException.java
  src/main/java/seedu/duke/exceptions/patient/invalidIDTypeException.java
  src/main/java/seedu/duke/exceptions/patient/invalidIDValueException.java
  src/main/java/seedu/duke/exceptions/patient/nonexistentIDException.java
  src/main/java/seedu/duke/menuparser/MenuParser.java
  src/main/java/seedu/duke/ui/UI.java
  src/main/java/seedu/patient/Patient.java
  src/main/java/seedu/patient/PatientCommandInstance.java
  src/main/java/seedu/patient/PatientList.java
Labels: priority.High, severity.Medium, type.Bug

#41 bug fix and improvement
  data/PatientList.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/ui/UI.java
Labels: priority.Medium, severity.Low, type.enhacement

#51 minor UI standardization for DoctorAppointment
  src/main/java/seedu/doctorappointments/DoctorAppointmentInstance.java
Labels: priority.Medium

#62 JAR no main manifest
  build.gradle
  src/main/resources/META-INF/MANIFEST.MF
Labels: priority.High

#68 v1.0 added JunitTest for Doctor Appointment
  src/test/java/seedu/doctorappointments/DoctorAppointmentParserTest.java
Labels: priority.Medium, type.enhacement

#84 added assertions
  src/main/java/seedu/duke/menuparser/NurseSchedulesParser.java
Labels: priority.High

#93 add JUnit Testing
  Staff.txt
  data/DoctorAppointmentList.txt
  data/PatientList.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/exceptions/patient/DuplicateIDException.java
  src/main/java/seedu/exceptions/patient/InvalidIDLengthException.java
  src/main/java/seedu/exceptions/patient/InvalidIDTypeException.java
  src/main/java/seedu/exceptions/patient/InvalidIDValueException.java
  src/main/java/seedu/exceptions/patient/NonExistentIDException.java
  src/main/java/seedu/logic/instance/PatientCommandInstance.java
  src/main/java/seedu/logic/parser/PatientParser.java
  src/main/java/seedu/storage/PatientStorage.java
  src/main/java/seedu/ui/PatientUI.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/patient/PatientParserTest.java
Labels: priority.Medium, severity.VeryLow

#95 Sort out NurseSchedule Developer guide
  docs/DeveloperGuide.md
  src/main/java/seedu/storage/NurseScheduleStorage.java
  src/test/java/seedu/nurseschedules/parser/NurseSchedulesParserTest.java
Labels: priority.High

#98 codebase edit post consultation + some UG for schedules added
  docs/UserGuide.md
  src/main/java/seedu/exceptions/nurseschedules/WrongInputsException.java
  src/main/java/seedu/logic/command/NurseScheduleActions.java
  src/main/java/seedu/logic/instance/NurseScheduleInstance.java
  src/main/java/seedu/logic/parser/NurseSchedulesParser.java
  src/main/java/seedu/ui/NurseScheduleUI.java
Labels: type.Task

#100 added more JUnit testing and checking methods
  NurseSchedules.txt
  src/main/java/seedu/logic/command/NurseScheduleActions.java
  src/main/java/seedu/logic/parser/NurseSchedulesParser.java
  src/main/java/seedu/model/object/NurseSchedule.java
  src/main/java/seedu/ui/NurseScheduleUI.java
  src/test/java/seedu/nurseschedules/parser/NurseSchedulesParserTest.java
Labels: type.enhacement

#105 Added OOP to schedules
  src/main/java/seedu/logic/command/Command.java
  src/main/java/seedu/logic/command/NurseScheduleActions.java
  src/main/java/seedu/logic/command/nurseschedule/NurseScheduleAdd.java
  src/main/java/seedu/logic/command/nurseschedule/NurseScheduleDelete.java
  src/main/java/seedu/logic/command/nurseschedule/NurseScheduleHelp.java
  src/main/java/seedu/logic/command/nurseschedule/NurseScheduleList.java
  src/main/java/seedu/logic/command/startmenu/ToNurseScheduleInstance.java
  src/main/java/seedu/logic/instance/NurseScheduleInstance.java
  src/main/java/seedu/logic/parser/NurseSchedulesParser.java
  src/main/java/seedu/storage/NurseScheduleStorage.java
  src/main/java/seedu/ui/NurseScheduleUI.java
  src/test/java/seedu/patient/PatientParserTest.java
Labels: priority.High

#107 Bug fixes, added smart command recognition and more error handling
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/logic/command/NurseScheduleActions.java
  src/main/java/seedu/logic/command/startmenu/ToNurseScheduleInstance.java
  src/main/java/seedu/logic/instance/NurseScheduleInstance.java
  src/main/java/seedu/logic/parser/NurseSchedulesParser.java
  src/main/java/seedu/logic/parser/StartMenuParser.java
  src/main/java/seedu/storage/NurseScheduleStorage.java
  src/main/java/seedu/ui/NurseScheduleUI.java
Labels: severity.Medium, type.Bug, type.Task

#110 changed delimiter to "/"
  src/main/java/seedu/logic/parser/NurseSchedulesParser.java
Labels: priority.High

#112 AppointmentParser Change delimeter to /
  data/DoctorAppointmentList.txt
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentAdd.java
  src/main/java/seedu/logic/parser/DoctorAppointmentParser.java
Labels: priority.Medium

#117 added command summary to UG
  docs/UserGuide.md
Labels: priority.High, type.Task

#119 Added exceptions and bugfixes
  data/Staff.txt
  src/main/java/seedu/exceptions/staff/BlankInputException.java
  src/main/java/seedu/logic/command/StaffAggregation.java
  src/main/java/seedu/logic/command/staff/StaffList.java
  src/main/java/seedu/logic/instance/StaffInstance.java
  src/main/java/seedu/logic/parser/staffparser.java
  src/main/java/seedu/ui/StaffUI.java
  src/main/java/seedu/ui/UI.java
Labels: severity.Medium

#122 Chiam jia en v2 eh
  src/main/java/seedu/exceptions/patient/IllegalCharacterException.java
  src/main/java/seedu/exceptions/patient/InvalidAgeException.java
  src/main/java/seedu/exceptions/patient/InvalidGenderException.java
  src/main/java/seedu/logic/command/patient/PatientAdd.java
  src/main/java/seedu/logic/parser/PatientParser.java
  src/main/java/seedu/logic/parser/StartMenuParser.java
  src/main/java/seedu/ui/PatientUI.java
  src/main/java/seedu/ui/UI.java
Labels: priority.High, severity.Medium, type.enhacement

#126 add more exception handling
  src/main/java/seedu/exceptions/patient/EmptyInputException.java
  src/main/java/seedu/logic/parser/PatientParser.java
Labels: priority.High, severity.Medium, type.Bug

#129 Doctor Appointment / Exception handling +add/list function
  data/DoctorAppointment.txt
  data/DoctorAppointmentList.txt
  data/Staff.txt
  src/main/java/seedu/exceptions/doctorappointment/AppointmentIDTakenException.java
  src/main/java/seedu/exceptions/doctorappointment/InvalidAppIDException.java
  src/main/java/seedu/exceptions/doctorappointment/InvalidDateException.java
  src/main/java/seedu/exceptions/doctorappointment/InvalidDocIDException.java
  src/main/java/seedu/exceptions/doctorappointment/InvalidGenderException.java
  src/main/java/seedu/exceptions/doctorappointment/InvalidIDException.java
  src/main/java/seedu/logic/command/AppointmentActions.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentAdd.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentDelete.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentList.java
  src/main/java/seedu/logic/instance/DoctorAppointmentInstance.java
  src/main/java/seedu/logic/parser/DoctorAppointmentParser.java
  src/main/java/seedu/storage/DoctorAppointmentStorage.java
  src/main/java/seedu/ui/DoctorAppointmentUI.java
Labels: priority.High, severity.High

#140 Further exception handling and standardised output
  src/main/java/seedu/exceptions/nurseschedules/NurseIdNotFound.java
  src/main/java/seedu/logic/command/NurseScheduleActions.java
  src/main/java/seedu/logic/instance/NurseScheduleInstance.java
  src/main/java/seedu/logic/parser/NurseSchedulesParser.java
  src/main/java/seedu/model/NurseSchedule.java
  src/main/java/seedu/ui/NurseScheduleUI.java
  src/test/java/seedu/nurseschedules/parser/NurseSchedulesParserTest.java
Labels: priority.High, severity.High, type.Task

#141 Bugfixes and Java CI fixes
  data/Staff.txt
  src/main/java/seedu/duke/Constants.java
  src/main/java/seedu/duke/HealthVault.java
  src/main/java/seedu/exceptions/CorruptedFileException.java
  src/main/java/seedu/exceptions/HealthVaultException.java
  src/main/java/seedu/logic/errorchecker/StaffChecker.java
Labels: priority.Medium, type.enhacement

#143 added data checking to Nurse Schedule Storage
  src/main/java/seedu/exceptions/nurseschedules/EmptyListException.java
  src/main/java/seedu/logic/command/NurseScheduleActions.java
  src/main/java/seedu/logic/errorchecker/NurseScheduleChecker.java
  src/main/java/seedu/logic/parser/NurseSchedulesParser.java
  src/main/java/seedu/storage/NurseScheduleStorage.java
  src/main/java/seedu/ui/NurseScheduleUI.java
Labels: priority.High, severity.High

#144 Bug fixes for escape char
  src/main/java/seedu/logic/errorchecker/MainChecker.java
Labels: severity.Medium, type.Bug

#145 Ignore duplicate id in txt file if file is edited
  data/Staff.txt
  src/main/java/seedu/exceptions/DuplicateIDException.java
  src/main/java/seedu/logic/command/StaffAggregation.java
  src/main/java/seedu/logic/parser/StaffParser.java
  src/main/java/seedu/model/staff/Staff.java
  src/main/java/seedu/storage/StaffStorage.java
Labels: severity.Low

#147 V2.0 DoctAppt Functionalities + AppointmentChecker updated
  src/main/java/seedu/logic/command/AppointmentActions.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentAdd.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentDelete.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentList.java
  src/main/java/seedu/logic/errorchecker/DoctorAppointmentChecker.java
  src/main/java/seedu/logic/parser/DoctorAppointmentParser.java
  src/main/java/seedu/logic/parser/NurseSchedulesParser.java
  src/main/java/seedu/storage/DoctorAppointmentStorage.java
  src/main/java/seedu/ui/DoctorAppointmentUI.java
  src/test/java/seedu/doctorappointments/DoctorAppointmentCheckerParserTest.java
Labels: priority.High, severity.High

#150 Fixed corrupted file handling
  data/Patients.txt
  src/main/java/seedu/exceptions/DuplicateIDException.java
  src/main/java/seedu/logic/command/StaffAggregation.java
  src/main/java/seedu/logic/command/staff/StaffAdd.java
  src/main/java/seedu/logic/errorchecker/StaffChecker.java
  src/main/java/seedu/logic/instance/StaffInstance.java
  src/main/java/seedu/logic/parser/StaffParser.java
  src/main/java/seedu/storage/StaffStorage.java
Labels: priority.Medium

#154 V2.0 DocApt Exception Handling and ErrorChecker Improvements
  data/DoctorAppointment.txt
  data/Staff.txt
  src/main/java/seedu/exceptions/InvalidIDException.java
  src/main/java/seedu/exceptions/doctorappointment/AppointmentIDTakenException.java
  src/main/java/seedu/exceptions/doctorappointment/FileCreatingErrorException.java
  src/main/java/seedu/exceptions/doctorappointment/InvalidAppIDException.java
  src/main/java/seedu/exceptions/doctorappointment/InvalidDateException.java
  src/main/java/seedu/exceptions/doctorappointment/InvalidDocIDException.java
  src/main/java/seedu/exceptions/doctorappointment/InvalidGenderException.java
  src/main/java/seedu/exceptions/doctorappointment/InvalidIDException.java
  src/main/java/seedu/exceptions/doctorappointment/WrongAptIDFormatException.java
  src/main/java/seedu/exceptions/doctorappointment/WrongInputException.java
  src/main/java/seedu/logic/command/Command.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentDelete.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentList.java
  src/main/java/seedu/logic/errorchecker/DoctorAppointmentChecker.java
  src/main/java/seedu/logic/instance/DoctorAppointmentInstance.java
  src/main/java/seedu/logic/parser/DoctorAppointmentParser.java
  src/main/java/seedu/storage/DoctorAppointmentStorage.java
Labels: priority.Medium

#157 added entry prevention, added CrossValidation error checking
  src/main/java/seedu/exceptions/nurseschedules/CrossValidationError.java
  src/main/java/seedu/logic/command/Command.java
  src/main/java/seedu/logic/command/NurseScheduleActions.java
  src/main/java/seedu/logic/command/nurseschedule/NurseScheduleAdd.java
  src/main/java/seedu/logic/command/nurseschedule/NurseScheduleListAll.java
  src/main/java/seedu/logic/errorchecker/NurseScheduleChecker.java
  src/main/java/seedu/logic/instance/NurseScheduleInstance.java
  src/main/java/seedu/storage/NurseScheduleStorage.java
  src/main/java/seedu/ui/NurseScheduleUI.java
Labels: priority.High, severity.High

#160 fixed minor bugs and checking
  .gitignore
  src/main/java/seedu/exceptions/patient/IllegalCharacterException.java
  src/main/java/seedu/logic/errorchecker/PatientChecker.java
  src/main/java/seedu/logic/instance/PatientCommandInstance.java
  src/main/java/seedu/storage/PatientStorage.java
  src/main/java/seedu/ui/PatientUI.java
Labels: priority.Medium, severity.Medium, type.Bug

#162 refactored illegalChar checker, small bug fixes
  src/main/java/seedu/logic/errorchecker/MainChecker.java
  src/main/java/seedu/logic/errorchecker/PatientChecker.java
  src/main/java/seedu/logic/parser/NurseSchedulesParser.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/nurseschedules/parser/NurseSchedulesParserTest.java
Labels: severity.Medium

#166 improved find function and improved format
  src/main/java/seedu/logic/command/PatientActions.java
  src/main/java/seedu/logic/errorchecker/PatientChecker.java
  src/main/java/seedu/logic/parser/PatientParser.java
  src/main/java/seedu/model/Patient.java
  src/main/java/seedu/ui/PatientUI.java
Labels: priority.Low, severity.Low, type.enhacement

#177 Added cross validation, duplicate Patient ID checking to Nurse Schedules
  docs/UserGuide.md
  src/main/java/seedu/exceptions/nurseschedules/NurseCrossValidationError.java
  src/main/java/seedu/exceptions/nurseschedules/PatientCrossValidationError.java
  src/main/java/seedu/exceptions/nurseschedules/PatientIdNotFound.java
  src/main/java/seedu/logic/command/Command.java
  src/main/java/seedu/logic/command/NurseScheduleActions.java
  src/main/java/seedu/logic/command/nurseschedule/NurseScheduleAdd.java
  src/main/java/seedu/logic/errorchecker/NurseScheduleChecker.java
  src/main/java/seedu/logic/instance/NurseScheduleInstance.java
  src/main/java/seedu/logic/parser/NurseSchedulesParser.java
  src/main/java/seedu/storage/NurseScheduleStorage.java
  src/main/java/seedu/ui/NurseScheduleUI.java
Labels: priority.High, severity.High

#180 Minor bug fixes and checkstyle edits
  src/main/java/seedu/duke/Constants.java
  src/main/java/seedu/logic/errorchecker/MainChecker.java
  src/main/java/seedu/logic/errorchecker/PatientChecker.java
  src/main/java/seedu/logic/instance/PatientCommandInstance.java
  src/main/java/seedu/logic/parser/PatientParser.java
  src/main/java/seedu/storage/PatientStorage.java
  src/main/java/seedu/ui/PatientUI.java
  src/main/java/seedu/ui/UI.java
Labels: priority.Medium, severity.Medium, type.Bug, type.enhacement

#182 V2.0 Cleared 31/3 Bug report for DocApt
  src/main/java/seedu/exceptions/doctorappointment/DocIDNotFoundException.java
  src/main/java/seedu/logic/command/AppointmentActions.java
  src/main/java/seedu/logic/command/doctorappointment/DoctorAppointmentList.java
  src/main/java/seedu/logic/errorchecker/DoctorAppointmentChecker.java
  src/main/java/seedu/logic/errorchecker/MainChecker.java
  src/main/java/seedu/logic/instance/DoctorAppointmentInstance.java
  src/main/java/seedu/storage/DoctorAppointmentStorage.java
  src/main/java/seedu/ui/DoctorAppointmentUI.java
Labels: priority.High, severity.High
